name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and tag the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pandoc-node:latest .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/pandoc-node:latest ${{ secrets.DOCKER_HUB_USERNAME }}/pandoc-node:${{ github.sha }}

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pandoc-latex-node:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pandoc-latex-node:${{ github.sha }}
